/* Importes en centavos: aritmética exacta equivalente a BigDecimal(2, HALF_UP). */
const IGV_INICIAL=0.18, redondear=v=>Math.round(v), dinero=c=>'$'+(c/100).toLocaleString('es-MX',{minimumFractionDigits:2,maximumFractionDigits:2});
class Producto{constructor(codigo,nombre,marca,precio,stock,art,badge=''){if(precio<=0||stock<0)throw Error('Precio y stock inválidos');Object.assign(this,{codigo,nombre,marca,precio,stock,art,badge})}}
class Cliente{constructor(nombre){if(!nombre||!nombre.trim())throw Error('El cliente es obligatorio');this.nombre=nombre.trim()}}
class DetalleVenta{constructor(p,cantidad){if(!Number.isInteger(cantidad)||cantidad<=0)throw Error('La cantidad debe ser positiva');Object.assign(this,{codigo:p.codigo,nombre:p.nombre,cantidad,precioUnitario:p.precio})}get importe(){return this.precioUnitario*this.cantidad}}
class Venta{constructor(cliente,detalles,tasa,descuento){this.id='V-'+Date.now().toString(36).toUpperCase();this.fecha=new Date().toLocaleString('es-MX');this.cliente=cliente.nombre;this.detalles=detalles;this.descuento=descuento;this.subtotal=detalles.reduce((s,d)=>s+d.importe,0);this.baseImponible=this.subtotal-descuento;this.igv=redondear(this.baseImponible*tasa);this.total=this.baseImponible+this.igv}}
class VentaService{constructor(productos){this.productos=productos;this.ventas=JSON.parse(localStorage.getItem('novacell-ventas')||'[]')}confirmar(cliente,items,tasa=IGV_INICIAL){if(!(cliente instanceof Cliente))throw Error('Cliente inválido');if(!items.length)throw Error('Agrega al menos un producto');const detalles=[];for(const item of items){const p=this.productos.find(x=>x.codigo===item.codigo);if(!p)throw Error(`Producto ${item.codigo} no existe`);if(!Number.isInteger(item.cantidad)||item.cantidad<=0)throw Error('La cantidad debe ser positiva');if(p.stock<item.cantidad)throw Error(`Stock insuficiente para ${p.nombre}`);detalles.push(new DetalleVenta(p,item.cantidad))}const subtotal=detalles.reduce((s,d)=>s+d.importe,0),descuento=detalles.reduce((s,d)=>s+(d.cantidad>=2?redondear(d.importe*.05):0),0);detalles.forEach(d=>this.productos.find(p=>p.codigo===d.codigo).stock-=d.cantidad);const venta=new Venta(cliente,detalles,tasa,descuento);this.ventas.unshift(venta);this.persist();return venta}persist(){localStorage.setItem('novacell-ventas',JSON.stringify(this.ventas));localStorage.setItem('novacell-productos',JSON.stringify(this.productos))}}
const inicial=[['P001','iPhone 15','Apple',1899900,3,'iphone','NUEVO'],['P002','Galaxy S24','Samsung',1699900,8,'samsung','POPULAR'],['P003','Redmi Note 13 Pro','Xiaomi',749900,6,'xiaomi',''],['P004','iPhone 13','Apple',1249900,4,'iphone',''],['P005','Galaxy A55','Samsung',899900,7,'samsung',''],['P006','Poco X6 Pro','Xiaomi',799900,5,'xiaomi','OFERTA']];
const guardados=JSON.parse(localStorage.getItem('novacell-productos')||'null');const productos=guardados?guardados.map(p=>Object.assign(new Producto(p.codigo,p.nombre,p.marca,p.precio,p.stock,p.art,p.badge),p)):inicial.map(p=>new Producto(...p));const ventaService=new VentaService(productos);let selectedCategory='Todos',carrito=[];const grid=document.querySelector('#product-grid');
function renderProducts(){const q=document.querySelector('#search').value.toLowerCase().trim(),visible=productos.filter(p=>(selectedCategory==='Todos'||p.marca===selectedCategory)&&`${p.marca} ${p.nombre}`.toLowerCase().includes(q));grid.innerHTML=visible.length?visible.map(p=>`<article class="product-card"><div class="product-image">${p.badge?`<span class="badge">${p.badge}</span>`:''}<div class="phone-art ${p.art}"></div></div><div class="product-info"><span class="brand">${p.marca.toUpperCase()}</span><h3>${p.nombre}</h3><p class="spec">${p.stock} disponibles · Precio de lista</p><div class="product-bottom"><span class="price">${dinero(p.precio)}</span><button class="add-button" data-add="${p.codigo}" ${p.stock===0?'disabled':''}>${p.stock?'Agregar +':'Agotado'}</button></div></div></article>`).join(''):'<p class="no-products">No encontramos celulares con esa búsqueda.</p>';document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>addToCart(b.dataset.add)))}
function addToCart(codigo){const p=productos.find(x=>x.codigo===codigo),item=carrito.find(x=>x.codigo===codigo);if(item)item.cantidad++;else carrito.push({codigo,cantidad:1});renderCart();showToast(`${p.nombre} se agregó al carrito`)}
function renderCart(){document.querySelector('#cart-count').textContent=carrito.reduce((s,i)=>s+i.cantidad,0);document.querySelector('#cart-items').innerHTML=carrito.length?carrito.map(i=>{const p=productos.find(x=>x.codigo===i.codigo);return `<div class="cart-item"><div><h3>${p.nombre} × ${i.cantidad}</h3><p>${dinero(p.precio)} c/u</p><button class="remove-item" data-remove="${p.codigo}">Eliminar</button></div><strong>${dinero(p.precio*i.cantidad)}</strong></div>`}).join(''):'<p class="empty-cart">Tu carrito está vacío.</p>';const subtotal=carrito.reduce((s,i)=>s+productos.find(p=>p.codigo===i.codigo).precio*i.cantidad,0),descuento=carrito.reduce((s,i)=>s+(i.cantidad>=2?redondear(productos.find(p=>p.codigo===i.codigo).precio*i.cantidad*.05):0),0),base=subtotal-descuento;document.querySelector('#cart-subtotal').textContent=dinero(base);document.querySelector('#cart-igv').textContent=dinero(redondear(base*IGV_INICIAL));document.querySelector('#cart-total').textContent=dinero(base+redondear(base*IGV_INICIAL));document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{carrito=carrito.filter(i=>i.codigo!==b.dataset.remove);renderCart()}))}
function renderManagement(){document.querySelector('#inventory-table').innerHTML=`<table><thead><tr><th>Producto</th><th>Precio</th><th>Stock</th></tr></thead><tbody>${productos.map(p=>`<tr><td>${p.nombre}</td><td>${dinero(p.precio)}</td><td class="${p.stock<2?'low-stock':''}">${p.stock}</td></tr>`).join('')}</tbody></table>`;document.querySelector('#sales-table').innerHTML=ventaService.ventas.length?`<table><thead><tr><th>Comprobante</th><th>Cliente</th><th>Total</th></tr></thead><tbody>${ventaService.ventas.map(v=>`<tr><td>${v.id}<small>${v.fecha}</small></td><td>${v.cliente}</td><td>${dinero(v.total)}</td></tr>`).join('')}</tbody></table>`:'<p class="empty-management">Todavía no hay ventas registradas.</p>'}
function toggleCart(open){document.querySelector('#cart-panel').hidden=!open;document.querySelector('#cart-overlay').hidden=!open;document.querySelector('#cart-panel').setAttribute('aria-hidden',String(!open))}function showToast(m){const t=document.querySelector('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
document.querySelectorAll('.category').forEach(b=>b.addEventListener('click',()=>{selectedCategory=b.dataset.category;document.querySelectorAll('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts()}));document.querySelector('#search').addEventListener('input',renderProducts);document.querySelector('#open-cart').addEventListener('click',()=>toggleCart(true));document.querySelector('#close-cart').addEventListener('click',()=>toggleCart(false));document.querySelector('#cart-overlay').addEventListener('click',()=>toggleCart(false));document.querySelector('#checkout').addEventListener('click',()=>{try{const venta=ventaService.confirmar(new Cliente(document.querySelector('#client-name').value),carrito,IGV_INICIAL);carrito=[];renderCart();renderProducts();renderManagement();toggleCart(false);showToast(`Venta ${venta.id} confirmada correctamente`)}catch(e){showToast(e.message)}});renderProducts();renderCart();renderManagement();
